### ISSUE TITLE
use of Rc limiting design possibility

### ISSUE THREAD

**Issue by jmhodges** [azasypkin/rust-cast#10]
The heavy use of Rc types means I can't construct a CastDevice on one thread and then move or clone it over to another thread (or thread pool) that my proxy server will be running on.

It's pretty common for networked clients to be thread-safe.

**Comment by azasypkin** [comment]
Yeah, that's the problem I'd like to solve as well whenever I have time. Marking this as a `good first issue` for now in case anyone else would like to tackle this.
