### ISSUE TITLE
Device discovery?

### ISSUE THREAD

**Issue by andrewshadura** [azasypkin/rust-cast#12]
Hi,

Unless I’m mistaken, there currently isn’t any code to discover new Chromecast devices, and the only way to use them is to know the IP address beforehand having discovered it by some other means. Would you consider implementing that *or* including some examples of performing discovery by other means (I’ve no idea at the moment how to do zeroconf discovery in Rust)?

**Comment by azasypkin** [comment]
Hey @andrewshadura,

> Unless I’m mistaken, there currently isn’t any code to discover new Chromecast devices, and the only way to use them is to know the IP address beforehand having discovered it by some other means.

Yeah, you're correct. 

> Would you consider implementing that or including some examples of performing discovery by other means (I’ve no idea at the moment how to do zeroconf discovery in Rust)?

I'd definitely accept PR if someone comes up with the solution for that (either as a part of this crate or just as an example)!

When I was toying with this crate in the past, I either used `avahi-browse` directly, like in [rust-caster example](https://github.com/azasypkin/rust-caster) (it can filter proper service types that Chromecast exposes) or used [multicast-dns](https://github.com/fxbox/multicast-dns) crate (basically a rough subset of Avahi bindings I wrote long time ago).

If you or anyone else have a desire to improve this crate even further, I think the proper direction would be to migrate to [Open Screen Protocol](https://github.com/w3c/openscreenprotocol) and Google's [openscreen library](https://chromium.googlesource.com/openscreen/) (assuming their license is permissive enough) that would give us a cross-platform access for the device discovery, support for all existing and future Chromecast-like devices (including Chromecast), and so on.

**Comment by JoelMon** [comment]
In case it's helpful to someone, the ~[Gnomecast](https://github.com/keredson/gnomecast) application~ [pychromecast](https://github.com/home-assistant-libs/pychromecast) library written in Python auto detects all casting abled devices in the network. Perhaps that functionality can be translated to rust-cast.

[This is the function](https://github.com/home-assistant-libs/pychromecast/blob/master/pychromecast/__init__.py#L179) that returns all of the connected casting devices.

**Comment by azasypkin** [comment]
Thanks to @CyrosX, we have a support for a device discovery via mDNS in the [rust_caster example](https://github.com/azasypkin/rust-cast/blob/main/examples/rust_caster.rs)! Refer to https://github.com/azasypkin/rust-cast/pull/18 for more details.
