### ISSUE TITLE
Is it possible to setup a continuous cast from a computer?

### ISSUE THREAD

**Issue by TriplEight** [azasypkin/rust-cast#14]
The idea is similar to the one in https://github.com/muammar/mkchromecast which sadly has quite a latency.

**Comment by denisidoro** [comment]
On a similar note: is it possible to stream local files?

**Comment by azasypkin** [comment]
> On a similar note: is it possible to stream local files?

It's not possible out-of-the box I believe since Chromecast doesn't have direct access to the local filesystem, but, theoretically, it should be trivial to spin-up a local HTTP server bound to 0.0.0.0 that can provide a HTTP/HTTPS link that we can send to the Chromecast.

**Comment by denisidoro** [comment]
Oh, I didn't imagine it would be that easy. I was under the impression that the server needed to implement a fancy protocol.

Just tested with `python3 -m http.server` for test purposes and it worked just fine!

**Comment by azasypkin** [comment]
Closing as there is nothing to do here, it seems.
