### ISSUE TITLE
Note: this works just fine with the latest Chromecast (Chomecast with Google TV)

### ISSUE THREAD

**Issue by dwlsalmeida** [azasypkin/rust-cast#15]
Hi there, I tested this with the latest Chromecast device: Chromecast with Google TV. The Big Buck Bunny example works just fine, i.e.:

```
cargo run --example rust_caster -- -a 192.168.15.19 -m http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4
```

**Comment by azasypkin** [comment]
Hey @dwlsalmeida,

Just to clarify, do you have any issue you wanted to report via this ticket or you just wanted to share that the lib works with `Google TV`?

**Comment by dwlsalmeida** [comment]
I just wanted to share that it works with Google TV yes, since the description says it has been tested only with Chromecast 2nd generation. I was actually going to submit a PR to update the README, but ended up not doing so.

**Comment by azasypkin** [comment]
> I just wanted to share that it works with Google TV yes, since the description says it has been tested only with Chromecast 2nd generation. I was actually going to submit a PR to update the README, but ended up not doing so.

Got it, thanks for the note! I'll update description to mention `Google TV` as well.
