### ISSUE TITLE
is it possible to use rustls instead of openssl ?

### ISSUE THREAD

**Issue by tsirysndr** [azasypkin/rust-cast#17]

**Comment by azasypkin** [comment]
It's not implemented, but I'd open to PR to either migrate to `rustls` completely or just add it behind a feature flag. There is no particular reason to rely on `openssl` in this crate, it just that when I created the first version of it `rustls` hasn't been released yet (~March, 2016)

**Comment by tsirysndr** [comment]
[rustls 0.21.0](https://www.memorysafety.org/blog/rustls-new-features/) has just been released, Rustls can now be used to establish TLS connections addressed by IP rather than by a domain name, so we can now try to implement rust-cast with rustls

**Comment by azasypkin** [comment]
> [rustls 0.21.0](https://www.memorysafety.org/blog/rustls-new-features/) has just been released, Rustls can now be used to establish TLS connections addressed by IP rather than by a domain name, so we can now try to implement rust-cast with rustls

Awesome, thanks for the update!

**Comment by CyrosX** [comment]
I've tried it a few times (also without cert verification and DNS name), but always got a handshake error. (UnexpectedEof)

**Comment by azasypkin** [comment]
> I've tried it a few times (also without cert verification and DNS name), but always got a handshake error. (UnexpectedEof)

It looks like @112RG made it work in https://github.com/azasypkin/rust-cast/pull/22. I'll review/check/merge once I get to my devices in mid-February.

**Comment by azasypkin** [comment]
Closed in https://github.com/azasypkin/rust-cast/pull/22, kudos to @112RG! Will be released in `0.19.0`.
