### ISSUE TITLE
Stream a local .mp4 file?

### ISSUE THREAD

**Issue by brandonros** [azasypkin/rust-cast#19]
`-m, --media <media_handle>              Media handle (URL for image or video, URL token for youtube video etc.) to load on the Cast connected device.`

seems to not support local files?

**Comment by azasypkin** [comment]
> seems to not support local files?

Yeah, unfortunately, it's not supported out of the box, but you can set up a local HTTP server to stream local files. See https://github.com/azasypkin/rust-cast/issues/14#issuecomment-1121413429

__Duplicate of:__ https://github.com/azasypkin/rust-cast/issues/14
